//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
/**
 * 打开相册基类
 */
namespace com.stanwind.unity3d{
	public abstract class StanImpl{
		/// <summary>
		/// open album action sheet
		/// </summary>
		public abstract void OpenPhoto ();
	}
}

